name: 'Retry a Workflow Run'
description: 'Retry a workflow run once or continuously until it passes.'
author: 'Your name or organization here'
inputs:
  token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
  once-label:
    description: Label for retrying a workflow once
    required: false
  continuous-label:
    description: Label for continously retrying a workflow
    required: false
  workflow:
    description: Workflow which should be retried
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
