name: Dependabot Merge

on:
  pull_request_target:
    types:
      - opened

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}
        uses: peter-evans/find-comment@v1
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '@dependabot merge'
      - run: |
          echo ${{ github.event.pull_request.user.login }}
          echo ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
          echo ${{ steps.find-comment.outputs.comment-id }}
          echo ${{ steps.find-comment.outputs.comment-body }}
      # - uses: peter-evans/create-or-update-comment@v1
      #   if: ${{ !steps.find-comment.outputs.comment-id }}
      #   with:
      #     comment-id: ${{ steps.find-comment.outputs.comment-id }}
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body: '@dependabot merge'
