name: Re-run Workflow

on:
  schedule:
    - cron: '*/30 * * * *'
  pull_request_target:
    types:
      - closed
      - labeled
      - unlabeled
  workflow_run:
    workflows:
      - Pull Request Fail
    types:
      - completed
  workflow_dispatch:

jobs:
  rerun-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Event Data
        run: |
          cat <<-'EOF'
            ${{ toJSON(github.event) }}
          EOF
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Re-run pull request workflows
        uses: ./
        with:
          token: ${{ secrets.GH_TOKEN }}
          once-label: ci-requeue
          continuous-label: ci-retry
          trigger-labels: ci-trigger
          workflow: pull-request-fail.yml
