name: Re-run Workflow

on:
  workflow_run:
    workflows:
      - pull-request-fail.yml
    types:
      - completed
  pull_request_target:
    types:
      - labeled
      - unlabeled
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  rerun-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Event Data
        run: echo '${{ toJSON(github.event) }}'
      - uses: actions/checkout@v2
      - name: Re-run pull request workflows
        uses: ./
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          once-label: ci-requeue
          continuous-label: ci-retry
          trigger-labels: ci-trigger
          workflow: pull-request-fail.yml
